# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
# rdiscount:
# extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://www.applitude.no
baseurl: /
title: Applitude studentforening
author: Applitude
description: Studentforening ved Universitetet i Oslo
avatar: banner.svg
avatar_height: 46
avatar_width: 316


email: kontakt@applitude.no
github: applitude # username
facebook: applitude
twitter: applitudeuio
# linkedin: username
# stackoverflow: username   #e.g: users/2735833/proton1h1
# Comment out if you don't want disqus
# disqus: username
google_analytics: UA-72562234-1


# needed for travis-ci build
exclude: [vendor]
