# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
# rdiscount:
# extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true
excerpt_separator: ""

# edit here to achieve your personal greatness
url: http://www.applitude.no
baseurl: "/"
title: Applsolutt studentforening
author: Applsolutt
description: Studentforening ved Universitetet i Oslo
avatar: "banner.svg"

email: kontakt@applitude.no
github: applitude # username
facebook: AppsoluttUiO
twitter: AppsoluttUiO
# linkedin: username
# stackoverflow: username   #e.g: users/2735833/proton1h1
# Comment out if you don't want disqus
# disqus: username
google_analytics: UA-72562234-1


# needed for travis-ci build
exclude: [vendor]
